name: easyauthorwebsites
favicon: null
layout_spectrum: 0.4043379647191614
typography_spectrum: 0.5238882773555815
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.5625
  lightness: 0.6195925143547356
  saturation: 0.9135625155176967
  rhythmicContrast: 0.6356315799057484
purpose: []
